version: '3.4'
services: 
  app:
    build: 
      context: .
      target: development
    container_name: app
    networks: 
      - deno-app-network
    volumes:
      - .:/usr/app
    ports: 
      - 3000:3000
    expose:
      - 3000

networks: 
  deno-app-network:
    driver: bridge
