version: '3'
services: 
  app:
    build: .
    container_name: app
    command: run --allow-env --allow-read -q src/index.ts
    networks: 
      - deno-app-network
    volumes: 
      - .:/app

networks: 
  deno-app-network:
    driver: bridge
